Add a parser
fedor-ivn/project-f pull request #21
Opened 2023-10-03 15:18 UTC by fedor-ivn

2023-10-03 16:42 UTC, SnejUgal requested changes
надеюсь очень скоро смёржим

2023-10-03 16:42 UTC, snejugal commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
```suggestion
```

или сделать как-нибудь чтоб флагом каким-нибудь настраивалось...

2023-10-03 16:42 UTC, snejugal commented on src/reader/element.h
> +    // std::optional<Cons> to_list() const;
а чоб не заимплементить?

2023-10-03 16:42 UTC, snejugal commented on src/reader/error.h
> +    UnclosedList
```suggestion
    UnclosedList,
```

2023-10-03 16:42 UTC, snejugal commented on src/reader/parser.cpp
> +
```suggestion
```

2023-10-03 16:42 UTC, snejugal commented on src/reader/parser.cpp
> +class ReachedEndOfFile {};
кажется не нужен нигде

2023-10-03 16:42 UTC, snejugal commented on src/reader/parser.h
> +
```suggestion
```

2023-10-03 16:42 UTC, snejugal commented on src/main.cpp
> +
```suggestion
```

2023-10-03 16:42 UTC, snejugal commented on src/reader/reader.h
> +    Reader(std::string_view source, Position position);
```suggestion
    Reader(std::string_view source, Position position = Position());
```

2023-10-03 16:42 UTC, snejugal commented on src/reader/reader.cpp
> +
вместе с предыдущим комментом

```suggestion
```

2023-10-03 16:42 UTC, SnejUgal commented on src/reader/parser.cpp
> +            std::make_unique<Cons>(Cons(this->parse_element(), token->span));
как будто конструктор без правого элемента используется только здесь. и к тому же у него ещё косяк со спаном

![image](https://github.com/fedor-ivn/project-f/assets/10610844/ce2d1b71-4893-4b89-ae09-0b79bdc361da)

конкретно здесь у Null можно было бы сделать спан 1:14..1:14. и соответственно на предпоследних двух строчках конец спана должен быть 1:14. если что, во всех других местах со спаном всё хорошо

2023-10-03 16:42 UTC, SnejUgal commented on src/reader/element.cpp
> +}
на всякий случай, я тут у себя сделал вывод с отступами, думаю можно прикрутить

```suggestion
void display_element(std::ostream& stream, const Element& element,
                     size_t depth) {
    if (element.is_null()) {
        stream << "Null";
    } else if (auto value = element.to_integer()) {
        stream << "Integer(" << *value << ")";
    } else if (auto value = element.to_real()) {
        stream << "Real(" << *value << ")";
    } else if (auto value = element.to_boolean()) {
        stream << "Boolean(" << *value << ")";
    } else if (auto value = element.to_symbol()) {
        stream << "Symbol(" << *value << ")";
    } else if (auto cons = dynamic_cast<const Cons*>(&element)) {
        std::string indentation;
        indentation.resize(depth * 2, ' ');
        stream << "Cons(\n" << indentation << "  ";
        display_element(stream, *cons->left, depth + 1);
        stream << ",\n" << indentation << "  ";
        display_element(stream, *cons->right, depth + 1);
        stream << ",\n" << indentation << ')';
    }

    stream << " at " << element.span;
}

std::ostream& element::operator<<(std::ostream& stream,
                                  const Element& element) {
    display_element(stream, element, 0);
    return stream;
}
```

2023-10-03 17:33 UTC, SnejUgal commented
блин, вот бы спан в этой ошибке показывал, где список начинается

![image](https://github.com/fedor-ivn/project-f/assets/10610844/312cba31-eb04-4d82-97c8-d4c7fb596954)

2023-10-04 21:41 UTC, ilnarkhasanov commented on src/reader/element.h
> +    // std::optional<Cons> to_list() const;
Го коммент уберем

2023-10-04 21:41 UTC, ilnarkhasanov commented on src/reader/element.h
> +} // namespace element
Тут тоже

2023-10-06 15:59 UTC, fedor-ivn commented on src/reader/element.h
> +} // namespace element
это clang добавил сам, мне кажется пусть будет, это наверное конвенция

2023-10-06 16:05 UTC, fedor-ivn commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
а может по дефолту такой оставить? а когда будем билдить на показ, то будем писать

```bash
cmake -DCMAKE_BUILD_TYPE=Release ...
```

иначе не очень юзабельно каждый раз опции огромные дописывать


или хочешь прям кастомный флаг добавить?

2023-10-07 07:23 UTC, SnejUgal commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
ну вообще достаточно один раз при настройке cmake добавить один флаг: `cmake -DCMAKE_BUILD_TYPE=Debug .`, потом `cmake --build .` будет собирать с дебаг символами. конфиг трогать не обязательно чтобы дебаг символы включить

2023-10-07 13:10 UTC, fedor-ivn commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
а как он это запоминает?... типо локальные какие-то конфиги выставляет при запуске `cmake -DCMAKE_BUILD_TYPE=Debug .`?

2023-10-07 13:18 UTC, SnejUgal commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
ну дык ты посмотри сколько фигни он генерит

![image](https://github.com/fedor-ivn/project-f/assets/10610844/df5db143-55e7-489c-a59a-9d3cb3e13007)

2023-10-07 13:24 UTC, fedor-ivn commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
мб в ридми тогда добавить инструкцию?

2023-10-07 13:24 UTC, SnejUgal commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
можно

2023-10-07 13:50 UTC, fedor-ivn commented on src/reader/parser.cpp
> +            std::make_unique<Cons>(Cons(this->parse_element(), token->span));
такое ожидается?

```
>>> 'func
Cons(
  Symbol(quote) at 1:1..1:2,
  Cons(
    Symbol(func) at 1:2..1:6,
    Null at 1:6..1:6,
  ) at 1:2..1:6,
) at 1:1..1:6
```

2023-10-07 14:16 UTC, fedor-ivn commented
> блин, вот бы спан в этой ошибке показывал, где список начинается
> 
> ![image](https://user-images.githubusercontent.com/10610844/272349521-312cba31-eb04-4d82-97c8-d4c7fb596954.png)
@SnejUgal так?
<img width="728" alt="image" src="https://github.com/fedor-ivn/project-f/assets/34605001/466a8e56-5b3d-46cc-8b39-aa57656e1d7b">

2023-10-07 14:17 UTC, SnejUgal commented on src/reader/parser.cpp
> +            std::make_unique<Cons>(Cons(this->parse_element(), token->span));
топ

2023-10-07 14:19 UTC, SnejUgal commented
@fedor-ivn ага, шикарно. можно сразу уточнить, какой спан будет если сразу несколько список незакрыто?

```lisp
(func testCons ()
    (and (equalList (cons 1 '(2 3)) '(1 2 3
```

2023-10-07 14:25 UTC, fedor-ivn commented
> @fedor-ivn ага, шикарно. можно сразу уточнить, какой спан будет если сразу несколько список незакрыто?
> 
> ```lisp
> (func testCons ()
>     (and (equalList (cons 1 '(2 3)) '(1 2 3
> ```

самый верхний. должно иначе быть?

<img width="721" alt="image" src="https://github.com/fedor-ivn/project-f/assets/34605001/c11c3c2b-7de4-4c25-8a2a-afad0ad6e96e">

2023-10-07 14:34 UTC, SnejUgal commented
@fedor-ivn в принципе окей, давай так будет

2023-10-07 18:52 UTC, SnejUgal commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
а конфиг-то вернёшь на место?

2023-10-07 19:03 UTC, ilnarkhasanov approved these changes

2023-10-07 19:04 UTC, SnejUgal approved these changes

2023-10-07 19:07 UTC, merged