Test-runner
fedor-ivn/project-f pull request #36
Opened 2023-10-10 16:39 UTC by ilnarkhasanov

2023-10-10 18:42 UTC, snejugal commented on CMakeLists.txt
> +)
![image](https://github.com/fedor-ivn/project-f/assets/10610844/0465517f-9b55-4742-8d04-af137a286ae8)
![image](https://github.com/fedor-ivn/project-f/assets/10610844/6654ca07-047e-4b78-a82b-752c99015007)

2023-10-10 18:42 UTC, SnejUgal commented on src/test_runner/main.cpp
> +}
мне кажется смысла разделять на два файла тут нет, можно всё в `src/test_runner.cpp` писать. класс тоже не нужно пилить кмк

2023-10-10 18:42 UTC, snejugal commented on src/test_runner/test_runner.cpp
> +    return false;
```suggestion
    return path.string().substr(path.string().length() - end.length()) == end;
```

2023-10-10 18:42 UTC, SnejUgal commented on src/test_runner/test_runner.cpp
> +    return false;
мб на с++20 переехать где есть ends_with...

2023-10-10 18:42 UTC, SnejUgal commented on src/test_runner/test_runner.cpp
> +    for (auto line : split(source, '\n')) {
мб построчно файл считывать? как в репле

2023-10-10 18:42 UTC, snejugal commented on src/test_runner/test_runner.cpp
> +    return passed;
```suggestion
            return false;
        } catch (reader::SyntaxError e) {
        }
    }

    return true;
```

2023-10-10 18:42 UTC, SnejUgal commented on src/test_runner/test_runner.cpp
> +bool TestRunner::parse_file(std::filesystem::path path) {
```suggestion
bool TestRunner::test_file(std::filesystem::path path) {
```

2023-10-10 18:42 UTC, SnejUgal commented on src/test_runner/test_runner.cpp
> +    }
```suggestion
    if (path_ends_with(path, ".fail.lispf")) {
        return test_fail_file(path);
    }
    return test_correct_file(path);
```

2023-10-10 18:42 UTC, SnejUgal commented on CMakeLists.txt
> +    src/reader/scanner.cpp
надо бы через либу сделать общие файлы

2023-10-10 19:11 UTC, fedor-ivn approved these changes

2023-10-10 19:12 UTC, fedor-ivn reviewed
с комментами Артема соглашусь, а так вроде все кул!

2023-10-13 19:33 UTC, SnejUgal commented on src/test_runner/test_runner.cpp
> +bool TestRunner::parse_file(std::filesystem::path path) {
вроде бы не resolved

2023-10-13 19:35 UTC, ilnarkhasanov commented on src/test_runner/test_runner.cpp
> +bool TestRunner::parse_file(std::filesystem::path path) {
Поменял
Сорян, походу случайно закрыл тред

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +    bool passed = true;
не меняется нигде. можно просто заинлайнить в ретурне

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +}
```suggestion
```

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +}
```suggestion
```

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +    file.close();
а ifstream разве не делает это сам?

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +    Reader reader((std::string_view(source)));
стоит либо переписать без passed, либо хотя бы сделать очевиднее, что значение `passed` определяется в try/catch

```suggestion
    Reader reader((std::string_view(source)));

    bool passed = true;
```

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +    std::string ext = ".lispf";
нужно ли это выносить в переменную, если всё равно используется только в одном месте?

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +    for (auto path : paths) {
```suggestion
    for (auto&& path : paths) {
```

а то копии за зря делает (вроде как)

2023-10-13 19:46 UTC, SnejUgal commented on src/test_runner.cpp
> +#include "reader/token.h"
вроде бы только error.h и reader.h нужны?

2023-10-13 19:47 UTC, SnejUgal commented on src/test_runner.cpp
> +    for (auto path : paths) {
как же хочется это на расте писать где проще следить за такими вещами...

2023-10-14 09:28 UTC, fedor-ivn requested changes

2023-10-14 09:28 UTC, fedor-ivn commented on src/test_runner.cpp
> +    test_all_files();
а может возвращать ненулевой код, если тесты фэйлятся?

2023-10-14 11:16 UTC, SnejUgal approved these changes

2023-10-14 12:00 UTC, fedor-ivn approved these changes

2023-10-14 12:44 UTC, merged