Add .gitignore
fedor-ivn/project-f pull request #4
Opened 2023-09-09 11:17 UTC by ilnarkhasanov

Add classes of tokens

2023-09-09 11:41 UTC, SnejUgal requested changes

2023-09-09 11:41 UTC, SnejUgal commented on src/reader/token.h
> +class Identifier : Token {};
а какой идентификатор? надо хранить в токене

2023-09-09 11:41 UTC, SnejUgal commented on src/reader/token.h
> +class Real : Token {};
какое число распарсилось тоже надо хранить

2023-09-09 11:41 UTC, SnejUgal commented on src/reader/token.h
> +class False : Token {};
нужен ещё токен для апострофа

2023-09-09 11:42 UTC, SnejUgal commented on src/reader/token.h
> +class False : Token {};
и для `null`

2023-09-09 13:57 UTC, ilnarkhasanov commented on src/reader/token.h
> +class False : Token {};
Мб для `True` и `False` сделаем просто тип `Boolean`?

2023-09-09 13:58 UTC, SnejUgal commented on src/reader/token.h
> +class False : Token {};
можно и так, если хранить значение в классе

2023-09-10 12:45 UTC, fedor-ivn commented on src/reader/token.h
> +class False : Token {};
тогда Boolean хранит enum уже ( `enum BooleanValues {true, false}`)

2023-09-10 13:02 UTC, SnejUgal commented on src/reader/token.h
> +class False : Token {};
слава богу в плюсах есть `bool`

2023-09-10 18:24 UTC, SnejUgal requested changes

2023-09-10 18:24 UTC, SnejUgal commented on .gitignore
> +build/
пофикси конец строки в конце файла

2023-09-10 18:24 UTC, SnejUgal commented on src/reader/scanner.cpp
> +    Token result;
Настрой форматтер `clangd` в вскоде, чтобы форматирование везде одинаковое было

2023-09-10 18:24 UTC, SnejUgal commented on src/reader/scanner.cpp
> +        return Null();
надо бы отдельный токен для eof

2023-09-10 18:24 UTC, SnejUgal commented on src/reader/scanner.h
> +  int current_index = 0;
```suggestion
  size_t current_index = 0;
```

2023-09-10 18:24 UTC, SnejUgal commented on src/reader/token.h
> +    int value;
```suggestion
    int64_t value;
```

с этим надо бы более точным быть

2023-09-10 18:24 UTC, SnejUgal commented on src/reader/token.h
> +    long double value;
```suggestion
    double value;
```

`long double` — это 128-битные флоуты

2023-09-10 18:33 UTC, SnejUgal commented on .gitignore
> +build/
![image](https://github.com/fedor-ivn/project-f/assets/10610844/f1b37e0b-73ee-48fb-a3a8-991f9ebee445)

2023-09-11 09:48 UTC, fedor-ivn commented on src/reader/token.h
> +class Eof : public Token {};
аббревиатура же, нет?

```suggestion
class EOF : public Token {};
```

2023-09-11 11:58 UTC, SnejUgal requested changes

2023-09-11 11:58 UTC, snejugal commented on src/reader/token.h
> +class Eof : public Token {};
```suggestion
class EndOfFile : public Token {};
```

2023-09-11 11:58 UTC, snejugal commented on src/reader/scanner.cpp
> +    else if (std::isdigit(source[current_index]) || source[current_index] == '-') {
плюс тоже может быть

2023-09-11 11:58 UTC, snejugal commented on src/reader/token.h
> +  double value;
а как потом это значение доставать?

2023-09-11 11:58 UTC, snejugal commented on src/reader/scanner.cpp
> +      return Identifier();
какой идентификатор?

2023-09-11 11:58 UTC, snejugal commented on src/reader/scanner.cpp
> +    return Null();
```suggestion
    return EndOfFile();
```

2023-09-11 11:58 UTC, snejugal commented on src/reader/token.h
>  #pragma once
```suggestion
#pragma once

#include <cstdint>
#include <string_view>
```

2023-09-11 11:58 UTC, snejugal commented on src/reader/scanner.cpp
> +      return Identifier();
парсинг идентификаторов и чисел стоит вынести в отдельные методы кмк

2023-09-11 11:58 UTC, snejugal commented on src/main.cpp
> +  std::string_view source("""(func ; a\nfoo ; b\n(1 ; c\n2.0 -3)\ntrue) ; ; ; ; ...""");
`"""` — это `""` и начало следующего строкого литерала, а не начало многострочного литерала, как в питоне

2023-09-11 11:58 UTC, SnejUgal commented on src/reader/scanner.cpp
> +        return Null();
@ilnarkhasanov помечай выполненные треды сделанными

2023-09-11 11:58 UTC, SnejUgal commented on src/reader/scanner.cpp
> +    std::cout << "LeftParenthesis" << std::endl;
все принты надо убрать из метода, а чтобы видеть, что всё работает хорошо, принты надо перенести в цикл в мейне

2023-09-11 11:58 UTC, SnejUgal commented on src/main.cpp
> +  }
чтобы перенести принт токенов в этот цикл, нам понадобится:

1. перепишем цикл так:

    ```cpp
      for (int source_index = 0; source_index < source.size(); source_index++){
        std::cout << scanner.next_token() << std::endl;
      }
    ```

2. добавим `friend`-функцию в `Token` для перегрузки `<<`:

    ```cpp
    class Token {
    public:
      friend std::ostream &operator<<(std::ostream &stream, const Token &token);
    };

3. добавим реализацию перегрузки:

    ```cpp
    #include <iostream>

    std::ostream &operator<<(std::ostream &stream, const Token &token) {
      if (const LeftParenthesis *t =
              dynamic_cast<const LeftParenthesis *>(&token)) {
        stream << "LeftParenthesis";
      } else ...

      return stream;
    }
    ```

4. сделаем `Token` полиморфным, чтобы работал `dynamic_cast`:

    ```cpp
    class Token {
    public:
      virtual ~Token() = default;

      friend std::ostream &operator<<(std::ostream &stream, const Token &token);
    };
    ```

5. запустим и осознаем, что при возвращении токена из `next_token` теряется информация о конкретном классе, потому что возвращаем просто `Token`. Добавим указатель:

    ```cpp
    #include <memory>

    class Scanner {
    public:
      std::unique_ptr<Token> next_token();
    ...
    }
    ```

6. исправим реализацию `next_token`:

    ```cpp
    std::unique_ptr<Token> Scanner::next_token() {
      if (current_index >= source.size()) {
        return std::make_unique<Null>(Null());
      }
      ...
    ```

7. Добавляем в цикл звёздочку перед `scanner.next_token()`, запускаем и наконец-то видим, что в терминал что-то выводится.

Вот так легко и просто мы сделали virtual dispatch на плюсах. Зато не раст с его `enum`, для которого virtual dispatch даже не понадобился бы.

2023-09-11 11:58 UTC, SnejUgal commented on src/main.cpp
> +  }
При исправлении реализации или хотя бы по выводу в терминале можно будет заметить, что пробелы сейчас не обрабатываются. А так-то сканнер должен их сам проскипать, пока не найдёт следующий токен, и вернуть его

2023-09-11 11:58 UTC, SnejUgal commented on src/main.cpp
> +  }
и да, этот цикл должен выводить токены, пока `next_token` не вернёт `EndOfFile`. сейчас условие цикла корявое

2023-09-11 12:09 UTC, fedor-ivn commented on src/reader/token.h
> +  double value;
`get_value()`🤡

2023-09-11 12:56 UTC, snejugal commented on src/reader/token.h
> +  double value;
жаль что на гитхабе нельзя клоунов ставить

2023-09-13 10:06 UTC, SnejUgal requested changes
не вижу парсинга `'` и `null`, надо добавить

2023-09-13 10:06 UTC, snejugal commented on src/reader/token.cpp
> +    stream << "LeftParenthesis\n";
мне кажется токену стоит печатать только себя, а перевод строки должен добавлять сам "пользователь". тогда, например, можно будет токены через запятую выводить, если надо

2023-09-13 10:06 UTC, snejugal commented on src/reader/scanner.h
> +  std::unique_ptr<Numeral> parse_numeral();
лучше в private занести

2023-09-13 10:06 UTC, snejugal commented on src/reader/scanner.cpp
>  Scanner::Scanner(std::string_view source) : source(source) {}
немного странно, что конструктор после методов определён

2023-09-13 10:06 UTC, snejugal commented on src/main.cpp
> +
```suggestion
```

2023-09-13 10:06 UTC, snejugal commented on src/reader/scanner.cpp
> +      }
стоит в parse_identifier перенести имхо

2023-09-13 10:06 UTC, snejugal commented on src/reader/scanner.cpp
> +  std::unique_ptr<Token> result = std::make_unique<Null>(Null());
предлагаю убрать этот `result`, скобки возвращать сразу же (строки 71-77) и там же инкрементить индексы как надо вместо строки 101. это же будет лучше работать, когда сделаешь цикл с поиском токена

2023-09-13 10:06 UTC, snejugal commented on src/reader/token.cpp
> +    }
```suggestion
    stream << "Boolean(" << t->value << ")";
```

вывод в ишью для примера, так-то лучше сделать максимально простой вывод

2023-09-13 10:06 UTC, snejugal commented on src/reader/token.cpp
> +    }
```suggestion
```

аналогично

2023-09-13 10:06 UTC, SnejUgal commented on src/reader/token.cpp
> +    stream << "Real " << t->value;
```suggestion
    stream << "Real(" << t->value << ")";
```

2023-09-13 10:06 UTC, SnejUgal commented on src/reader/token.cpp
> +    stream << "Integer " << t->value << '\n';
```suggestion
    stream << "Integer(" << t->value << ")";
```

2023-09-13 10:06 UTC, SnejUgal commented on src/reader/token.cpp
> +    stream << "Identifier `" << t->value << "`\n";
```suggestion
    stream << "Identifier(" << t->value << ")";
```

2023-09-14 08:43 UTC, SnejUgal requested changes

2023-09-14 08:43 UTC, SnejUgal commented on src/reader/scanner.cpp
> +            current_index < source.size()) {
```suggestion
        while (source[current_index] != '\n' && current_index < source.size()) {
```

2023-09-14 08:43 UTC, SnejUgal commented on src/reader/scanner.cpp
> +    current_index++;
ну это ж не так если у тебя число или идентификатор был

2023-09-14 10:51 UTC, SnejUgal commented on src/reader/scanner.cpp
> +    while ((source[current_index] == ' ' || source[current_index] == '\n') &&
лучше бы `isspace` использовать, чтобы учитывались табы и другие пробелы 

https://en.cppreference.com/w/cpp/string/byte/isspace

2023-09-15 12:57 UTC, snejugal reviewed
Что-то с форматированием

![image](https://github.com/fedor-ivn/project-f/assets/10610844/578bb3ec-7765-4bed-8f3e-542b74a63388)
![image](https://github.com/fedor-ivn/project-f/assets/10610844/d4e01bf1-1951-403a-baf3-41818af71833)

отформатируй и апрувну

2023-09-15 18:07 UTC, SnejUgal approved these changes

2023-09-16 20:58 UTC, fedor-ivn reviewed
Код прям приятно читать 😌 

Ильнар, красава!

2023-09-16 20:58 UTC, fedor-ivn commented on src/reader/scanner.cpp
> +    current_index++;
почему решил так не писать? менее читаемо типо?
```suggestion
    int begin_index = current_index++;
```

2023-09-16 20:58 UTC, fedor-ivn commented on src/reader/scanner.cpp
> +            }
может быть вынести парсинг кейвордов в отдельный метод?

имхо next_token большеват сейчас и много вложенности

2023-09-16 20:58 UTC, fedor-ivn commented on src/reader/token.cpp
возможно пропустил дискуссию, но почему тут полиморфизм было не заюзать? типо определить свой `<<` для каждого наследника токена. 

единственное, чот не помню как в плюсах абстрактные фриенд функции делать и как там чо

2023-09-17 06:04 UTC, SnejUgal commented on src/reader/token.cpp
абстрактных друзей в плюсах нет

можно сделать в class Token такой метод:

```cpp
virtual void display(std::ostream& stream) = 0;
```

и заюзать его в реализации друга. только вот потом в каждом наследующемся классе надо будет указывать, что ты этот метод реализуешь в этом классе

```cpp
class LeftParenthesis : public Token {
    virtual void display(std::ostream& stream);
}

class RightParenthesis : public Token {
    virtual void display(std::ostream& stream);
}
```

думаю видно, куда это ведёт. поэтому я предложил способ с dynamic_cast

2023-09-17 06:06 UTC, SnejUgal commented on src/reader/scanner.cpp
> +            }
я бы перенёс в parse_identifier пожалуй

2023-09-17 06:15 UTC, fedor-ivn commented on src/reader/token.cpp
okay got it

2023-09-17 08:53 UTC, SnejUgal commented on src/reader/scanner.cpp
> +        return result;
можно же сразу вернуть не создавая переменную

2023-09-17 13:49 UTC, fedor-ivn approved these changes

2023-09-17 13:49 UTC, fedor-ivn commented on src/reader/scanner.cpp
> +
```suggestion
```

2023-09-17 13:51 UTC, SnejUgal commented on src/reader/scanner.cpp
> +            return result;
```suggestion
            return parse_symbol();
```

и ниже тоже тогда

2023-09-17 13:51 UTC, SnejUgal commented on src/reader/scanner.cpp
> +
https://github.com/fedor-ivn/project-f/pull/4/files/831601d4d5c17eb80cdff45e5ff32ad1a7d6b373#r1328096834

2023-09-17 13:52 UTC, SnejUgal commented on src/reader/scanner.cpp
> +        } else if (source[current_index] == '\'') {
а это не может быть в switch'е?

2023-09-17 14:14 UTC, SnejUgal commented on src/reader/scanner.cpp
> +        return result;
```suggestion
        return parse_numeral();
```

2023-09-17 14:27 UTC, merged