Fedorivn parse expressions
fedor-ivn/project-f pull request #47
Opened 2023-11-02 13:24 UTC by fedor-ivn

2023-11-02 18:38 UTC, ilnarkhasanov requested changes

2023-11-02 18:38 UTC, ilnarkhasanov commented on src/evaluator/program.cpp
> +#include <algorithm>
```suggestion
```

2023-11-02 18:38 UTC, ilnarkhasanov commented
Остальное всё хорошо

2023-11-03 10:14 UTC, SnejUgal requested changes

2023-11-03 10:14 UTC, SnejUgal commented on src/evaluator/program.cpp
> +            "`while` takes 2 arguments, provided more than two"
`while` берёт сколько угодно аргументов, все что идёт после условия должно быть телом. так же, как с `func`

2023-11-03 11:25 UTC, fedor-ivn commented on src/evaluator/program.cpp
> +            "`while` takes 2 arguments, provided more than two"
чот из сигнатуры непонятно было, что там может быть больше двух аргументов

<img width="556" alt="image" src="https://github.com/fedor-ivn/project-f/assets/34605001/7e6549da-97d8-4bbd-abeb-fe530df64dc8">

2023-11-03 11:26 UTC, SnejUgal commented on src/evaluator/program.cpp
> +            "`while` takes 2 arguments, provided more than two"
https://hackmd.io/@snejugal/B1D9F5QC3

2023-11-03 13:24 UTC, ilnarkhasanov approved these changes

2023-11-03 13:30 UTC, SnejUgal approved these changes

2023-11-03 13:39 UTC, merged