Draft: Add tests for built-in functions
fedor-ivn/project-f pull request #5
Opened 2023-09-10 12:59 UTC by SnejUgal

2023-09-10 18:26 UTC, ilnarkhasanov requested changes

2023-09-10 18:26 UTC, ilnarkhasanov commented on tests/functions/arithmetic.lispf
> +         (equal (plus 0.125 1) 1.255)
1.125

2023-09-11 19:15 UTC, fedor-ivn approved these changes

2023-09-11 19:15 UTC, fedor-ivn commented on tests/semantic/prog.lispf
> +; test prog-local varables
```suggestion
; test prog-local variables
```

2023-09-12 19:12 UTC, ilnarkhasanov approved these changes

2023-09-12 19:20 UTC, merged