Test runner supports semantic tests
fedor-ivn/project-f pull request #65
Opened 2023-11-12 07:37 UTC by ilnarkhasanov

2023-11-12 10:01 UTC, SnejUgal requested changes

2023-11-12 10:01 UTC, snejugal commented on src/test_runner.cpp
> +    Parser parser(scanner);
можно просто ридер использовать

2023-11-12 10:01 UTC, snejugal commented on src/test_runner.cpp
> +    }
```suggestion
    if (!boolean) {
        return false;
    }
```

2023-11-12 10:01 UTC, snejugal commented on src/test_runner.cpp
> +        Arguments::print_help(program_name);
```suggestion
        Arguments::print_help(program_name);
        return 0;
```

2023-11-12 10:01 UTC, snejugal commented on src/test_runner.cpp
> +        Arguments::print_help(program_name);
ну и я бы не стал help объединять с mode, чтоб не было непонятного состояния когда функциям надо обработать странный режим `HELP`

2023-11-12 10:01 UTC, SnejUgal commented on src/test_runner.cpp
> +    std::string postfix = mode == Mode::SEMANTIC ? "semantic" : "syntax";
```suggestion
    std::string subdirectory = mode == Mode::SEMANTIC ? "semantic" : "syntax";
```

2023-11-12 10:01 UTC, SnejUgal commented on src/test_runner.cpp
> +    std::string postfix = mode == Mode::SEMANTIC ? "semantic" : "syntax";
и по идее тесты на функции стоит вместе с "семантическими" тестами запускать (функция тоже семантика)

2023-11-13 17:14 UTC, SnejUgal commented on src/test_runner.cpp
> +#include "reader/scanner.h"
```suggestion
#include "reader/reader.h"
```

2023-11-13 17:59 UTC, snejugal commented on src/test_runner.cpp
> +    for (std::string_view subdirectory : subdirectories) {
```suggestion
    for (auto subdirectory : subdirectories) {
```

2023-11-13 17:59 UTC, snejugal commented on src/test_runner.cpp
> +    return 0;
не возвращаешь ошибку если тесты зафейлились

2023-11-13 17:59 UTC, snejugal commented on src/test_runner.cpp
> +    Mode get_mode() { return this->mode; }
сделай просто публичным. ты же с интерпретатора слизывал парсер аргументов, зачем от него отходить

2023-11-13 17:59 UTC, snejugal commented on src/test_runner.cpp
> +        }
и `--help` имхо стоит парсить так же, как в интерпретаторе. кидать ошибку на что-то типа `./test-runner --help -blahblahblah` фигово, потому что я добавил флаг `--help`, а хелпа не вижу, а удалять старые флаги было лень

2023-11-13 18:44 UTC, SnejUgal commented on src/test_runner.cpp
> +        }
всё ещё хочется, чтоб было поле `help`, как в интерпретаторе, и справку печатал мейн, а не парсер аргументов

2023-11-14 18:17 UTC, SnejUgal commented on src/test_runner.cpp
> +enum class Mode { SYNTAX, SEMANTIC };
почему-то только сейчас обратил на это внимание

а запуск синтаксических тестов и запуск семантических тестов --- точно взаимноисключающие действия?

2023-11-15 12:47 UTC, SnejUgal requested changes

2023-11-15 12:47 UTC, SnejUgal commented on src/test_runner.cpp
> +    auto program = Program::parse(reader.read());
```suggestion
    Program program;
    try {
        Reader reader(source);
        program = Program::parse(reader.read());
    } catch (SyntaxError const&) {
        return false;
    } catch (EvaluationError const&) {
        return false;
    }
```

вот бы ещё как-то причину фейла сообщать

2023-11-15 12:47 UTC, SnejUgal commented on src/test_runner.cpp
> +    std::vector<std::filesystem::path> paths = get_paths(Mode::SEMANTIC);
предлагаю, чтоб функция принимала список тестов, а не сама их искала

2023-11-15 12:47 UTC, SnejUgal commented on src/test_runner.cpp
> +    std::vector<std::filesystem::path> paths = get_paths(Mode::SYNTAX);
аналогично

2023-11-15 12:47 UTC, SnejUgal commented on src/test_runner.cpp
> +  public:
```suggestion
  public:
    std::vector<std::path> files;
```

если хотим возможность указывать отдельный файл, не вижу смысла ограничиваться одним файлом

2023-11-15 12:47 UTC, SnejUgal commented on src/test_runner.cpp
> +    Mode mode;
точно нужно?

если указаны какие-то файлы — значит запускаем их все как семантические тесты (проверить, что файл просто парсится, можно и интерпретатором). если не указаны — запускаем те, что в tests лежат

2023-11-18 12:03 UTC, snejugal commented on src/test_runner.cpp
> +                         "but it is actucally not.";
it is not syntactially incorrect --- сложно читается

```suggestion
            std::cout << "This file is supposed to be syntactically incorrect, "
                         "but it parsed without errors";
```

2023-11-18 12:03 UTC, snejugal commented on src/test_runner.cpp
> +    }
в принципе синтаксическая ошибка тоже может закрасться

2023-11-18 12:03 UTC, SnejUgal commented on src/test_runner.cpp
> +        for (auto path : arguments.files) {
идея прокидывать в `test_files_syntax` и `test_files_semantic` была в том, чтобы было можно туда прокидывать файлы из командной строки и иметь одну логику вне зависимости от того, как мы получили список файлов

2023-11-18 13:47 UTC, ilnarkhasanov commented on src/test_runner.cpp
> +    }
Мы их ловим до семантических тестов. И если поймали, то раннер стопается

2023-11-19 05:41 UTC, SnejUgal commented on src/test_runner.cpp
> +    }
если запустить тест-раннер без передачи файлов через аргументы, то на файлах с семантическими тестами он запустит только эту функцию, и если там будет синтаксическая ошибка, то всё накроется. плюсом, если здесь ловить синтаксические ошибки, то не нужно будет отдельно запускать синтаксические тесты, если передали список файлов

2023-11-19 05:58 UTC, SnejUgal requested changes

2023-11-19 05:58 UTC, SnejUgal commented on src/test_runner.cpp
> +    void parse(int argc, char const** argv) {
сейчас логика парсинга слишком перемудрённая

получается, тест раннер можно запускать так:

```
./test-runner
./test-runner --syntax
./test-runner --semantic
./test-runner --help
./test-runner ...files
```

соответственно смотришь: если аргумент один и такой-то флаг, то парсишь этот флаг; если нет, то идёшь парсить список файлов

2023-11-19 05:58 UTC, SnejUgal commented on src/test_runner.cpp
> +            this->mode = Mode::SEMANTIC;
лучше задать значение поля по умолчанию

2023-11-19 05:58 UTC, SnejUgal commented on src/test_runner.cpp
> +            }
совет в целом: если на первой/последней итерации цикла нужна совершенно другая логика, чем на остальных, то эту логику стоит вынести до/после цикла, а цикл прогонять только на оставшихся элементах

2023-11-19 05:58 UTC, SnejUgal commented on src/test_runner.cpp
> +                }
совет в целом: аргументы лучше так парсить: чекаешь, что в начале аргумента есть дефис. если есть, то пытаешься распарсить флаг, если не получилось — кидаешь ошибку о неизвестном флаге. иначе `./test-runner --semntic` попробует запустить тест, вместо того чтобы указать на опечатку

2023-11-19 11:27 UTC, SnejUgal commented on src/test_runner.cpp
> +        }
вот такое очень fragile: никто не гарантирует, что к моменту использования файл всё ещё будет, см [tocttou](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use)

2023-11-19 16:49 UTC, SnejUgal commented on src/test_runner.cpp
> +        }
всё равно может оказаться, что файла не будет... если тебе надо юзать файл, то вообще не надо отдельно проверять, существует ли он: просто открываешь и там уже по факту смотришь, открылся ли он. вдобавок стоит сделать, чтоб если файла на самом деле не оказалось, то валится только он, а не весь тест-раннер. вот делай вот так:

https://github.com/fedor-ivn/project-f/blob/8cb94747b1dd3491b196b0d09cd2f09488608478/src/main.cpp#L256-L257

и если файл не открылся, то печатаешь в консоль, что файла нет, и считаешь, что тест завалился. заодно уберёшь FileDoesNotExist

2023-11-19 16:54 UTC, SnejUgal commented on src/test_runner.cpp
> +        }
по остальному коду замечаний нет, пофиксишь и апрувну наконец-то

2023-11-19 19:09 UTC, SnejUgal approved these changes

2023-11-22 13:05 UTC, fedor-ivn approved these changes

2023-11-22 13:14 UTC, merged