Evaluate prog
fedor-ivn/project-f pull request #66
Opened 2023-11-12 08:43 UTC by ilnarkhasanov

2023-11-12 09:48 UTC, SnejUgal requested changes

2023-11-12 09:48 UTC, SnejUgal commented on src/evaluator/expression/prog.cpp
> +    std::shared_ptr<Scope> local_scope =
```suggestion
    auto local_scope =
```

2023-11-12 09:48 UTC, SnejUgal commented on src/evaluator/expression/prog.cpp
> +        auto v = parameter;
?

2023-11-12 09:48 UTC, SnejUgal commented on src/evaluator/expression/prog.cpp
> +            *parameter, std::make_shared<ast::Null>(Null(this->span))
```suggestion
            *parameter, std::make_shared<ast::Null>(Null(parameter->span))
```

так точнее

2023-11-12 09:48 UTC, SnejUgal commented on src/evaluator/expression/prog.cpp
> +        }
`breaks` это для тайп-чекера, чтобы знать когда выражение точно-точно сделает break, потому что это влияет на тип результата. ты не покрываешь случай, когда оно не прям точно-точно делает break (`(cond x (break 1))`), и ты не возвращаешь значение, которое прокидывает break (`(break (plus x 2))`)

break можно запилить так: при вычислении `break` кидает какой-нибудь `BreakControlFlow`, положив туда нужное значение, а `prog` его ловит и обрабатывает нужным образом

2023-11-12 09:48 UTC, SnejUgal commented on src/evaluator/expression/prog.cpp
> +    std::shared_ptr<ast::Element> result;
тело вполне может быть пустым (грамматика не запрещает), в этом случае надо возвращать `null`

2023-11-13 18:34 UTC, ilnarkhasanov commented on src/evaluator/expression/prog.cpp
> +        auto v = parameter;
Сорян

2023-11-14 18:24 UTC, SnejUgal commented on src/evaluator/expression/prog.cpp
> +    std::shared_ptr<ast::Element> result;
```suggestion
    std::shared_ptr<ast::Element> result = std::make_shared<Null>(this->span);
```

2023-11-15 12:37 UTC, SnejUgal approved these changes

2023-11-19 08:22 UTC, fedor-ivn approved these changes

2023-11-19 10:08 UTC, merged