Implement evaluation of while
fedor-ivn/project-f pull request #67
Opened 2023-11-12 09:07 UTC by ilnarkhasanov

2023-11-12 09:51 UTC, SnejUgal requested changes

2023-11-12 09:51 UTC, SnejUgal commented on src/evaluator/expression/while.cpp
> +        }
аналогичный момент про `break`, как и в `prog`

2023-11-12 09:51 UTC, SnejUgal commented on src/evaluator/expression/while.cpp
> +            result = expression->evaluate(scope);
`while` всегда возвращает `null`

2023-11-17 13:44 UTC, SnejUgal commented on src/evaluator/expression/while.cpp
> +                return std::make_shared<Null>(Null(this->span));
```suggestion
                break;
```

2023-11-17 13:44 UTC, SnejUgal commented on src/evaluator/expression/while.cpp
> +    std::shared_ptr<Element> result;
а зачем?

2023-11-17 13:49 UTC, ilnarkhasanov commented on src/evaluator/expression/while.cpp
> +                return std::make_shared<Null>(Null(this->span));
Если мы здесь поставим break, то мы опять зайдём в цикл, которые делает все проверки и прогоняет выражение. Хендлить там то что мы брейкнулись не особо хочется, поэтому так решил сделать

![image](https://github.com/fedor-ivn/project-f/assets/37439026/27f7040b-47cf-495b-9345-eb17992358f2)

2023-11-17 13:50 UTC, ilnarkhasanov commented on src/evaluator/expression/while.cpp
> +                return std::make_shared<Null>(Null(this->span));
Щас бы в раст, где для этого есть фича...

2023-11-17 13:51 UTC, SnejUgal commented on src/evaluator/expression/while.cpp
> +                return std::make_shared<Null>(Null(this->span));
а, это внутренний цикл... разве в плюсах нет циклов с лейблами?

2023-11-17 13:53 UTC, SnejUgal commented on src/evaluator/expression/while.cpp
> +                return std::make_shared<Null>(Null(this->span));
впрочем, имхо ловить break стоит прям снаружи внешего цикла, потому что а зачем запрещать `break` в условии цикла (в расте так можно например, только надо лейблов нацепить)

2023-11-17 13:53 UTC, ilnarkhasanov commented on src/evaluator/expression/while.cpp
> +                return std::make_shared<Null>(Null(this->span));
Вроде только `goto` есть
Предлагаю не пачкать этим руки

2023-11-17 15:33 UTC, SnejUgal approved these changes

2023-11-19 08:22 UTC, fedor-ivn approved these changes

2023-11-19 10:07 UTC, merged