Evaluate equal
fedor-ivn/project-f pull request #72
Opened 2023-11-18 14:52 UTC by ilnarkhasanov

2023-11-18 14:59 UTC, SnejUgal requested changes

2023-11-18 14:59 UTC, SnejUgal commented on src/evaluator/function/comparisons.cpp
> +        }
сделай в начале проверку, что `a` и `b` одного типа (у нас там появилось поле `type` недавно). если не одного типа, то кидаешь эту ошибку, а если всё окей, то считаешь, что если одно скастилось, то скастится и другое

2023-11-18 14:59 UTC, SnejUgal commented on src/evaluator/function/comparisons.cpp
> +            result = a == b;
```suggestion
            result = a_real->value == b_real->value;
```

2023-11-18 14:59 UTC, SnejUgal commented on src/evaluator/function/comparisons.cpp
> +            "Integer, Real, Boolean",
```suggestion
            "`equal` expects arguments to be both either integers, reals, or booleans"
```

2023-11-18 14:59 UTC, SnejUgal commented on src/evaluator/function/comparisons.cpp
> +    return result_element;
```suggestion
    return std::make_shared<ast::Boolean>(result, this->span);
```

не помню, говорил ли уже, что оказца make_shared и так перенаправляет аргументы конструктору, поэтому это немного излишне (знал бы я раньше (а лучше бы не писал на минусах))

2023-11-18 14:59 UTC, SnejUgal commented on src/evaluator/function/comparisons.cpp
> +    stream << "element element";
```suggestion
    stream << "a b";
```

не могут же параметры иметь одинаковое имя

2023-11-18 17:29 UTC, SnejUgal requested changes

2023-11-18 17:29 UTC, SnejUgal commented on src/evaluator/function/logical.cpp
> +    if (a_element->kind != b_element->kind) {
```suggestion
    if (a_element->kind != ElementKind::BOOLEAN || b_element->kind != ElementKind::BOOLEAN) {
```

2023-11-18 17:29 UTC, SnejUgal commented on src/evaluator/function/logical.cpp
> +    }
```suggestion
    auto a_bool = std::dynamic_pointer_cast<ast::Boolean>(a_element);
    auto b_bool = std::dynamic_pointer_cast<ast::Boolean>(b_element);
    auto result = a_bool->value && b_bool->value;
```

2023-11-18 17:29 UTC, SnejUgal commented on src/evaluator/function/logical.cpp
> +    }
ну и ниже аналогично

2023-11-18 17:29 UTC, SnejUgal commented on src/evaluator/function/logical.cpp
> +        result = !(element_bool->value);
```suggestion
        result = !element_bool->value;
```

2023-11-18 17:29 UTC, SnejUgal commented on src/evaluator/function/comparisons.cpp
> +    } else {
~~зато не паттерн-матчинг на адт~~

2023-11-19 04:47 UTC, SnejUgal commented on src/evaluator/function/logical.cpp
> +    result = a_bool->value && b_bool->value;
```suggestion
    auto a_bool = std::dynamic_pointer_cast<ast::Boolean>(a_element);
    auto b_bool = std::dynamic_pointer_cast<ast::Boolean>(b_element);
    auto result = a_bool->value && b_bool->value;
```

ну и аналогично в остальных функциях

2023-11-19 04:47 UTC, SnejUgal commented on src/evaluator/function/logical.cpp
> +            "`not` expects argument to be boolean", frame.call_site
```suggestion
            "`not` expects its argument to be a boolean", frame.call_site
```

2023-11-19 10:07 UTC, SnejUgal approved these changes

2023-11-22 13:08 UTC, fedor-ivn approved these changes

2023-11-22 13:14 UTC, merged